import os from 'node:os';
import path from 'node:path';
import {DurableOutbox} from './outbox.js';
import {BatchUploader} from './uploader.js';
import {SecondaryBridge} from './bridge.js';
import {DurableGroupState} from './group-state.js';

const endpoint=process.env.RADAR_BRIDGE_INGEST_URL,token=process.env.RADAR_BRIDGE_INGEST_TOKEN;
if(!endpoint||!token)throw new Error('Configura RADAR_BRIDGE_INGEST_URL y RADAR_BRIDGE_INGEST_TOKEN fuera de Git.');
const runtimeRoot=process.env.RADAR_BRIDGE_RUNTIME_DIR||path.join(process.env.LOCALAPPDATA||os.homedir(),'RadarInmobiliario','whatsapp-secondary');
const [whatsappModule,qrModule]=await Promise.all([import('whatsapp-web.js'),import('qrcode-terminal')]);
const {Client,LocalAuth}=whatsappModule.default||whatsappModule;
const qr=qrModule.default||qrModule;
const client=new Client({authStrategy:new LocalAuth({clientId:'radar-v061-secondary',dataPath:path.join(runtimeRoot,'session')}),puppeteer:{headless:true,args:['--no-sandbox','--disable-setuid-sandbox']}});
const LOG_FIELDS=new Set(['count','status','retryInMs','operation','attempt','scope','errorName']);
const safeLog=(event,data={})=>console.log(JSON.stringify({at:new Date().toISOString(),event,...Object.fromEntries(Object.entries(data).filter(([key])=>LOG_FIELDS.has(key)))}));
const outbox=new DurableOutbox(path.join(runtimeRoot,'outbox','events.json'));
const uploader=new BatchUploader({outbox,endpoint,token,logger:safeLog});
const groupState=new DurableGroupState(path.join(runtimeRoot,'state','groups.json'));
const bridge=new SecondaryBridge({client,outbox,uploader,groupState,logger:safeLog});
bridge.onQr=value=>qr.generate(value,{small:true});bridge.wire();
process.on('SIGINT',async()=>{bridge.stopFlushLoop();await client.destroy();process.exit(0);});
await client.initialize();
