import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {chromiumCandidates,discoverChromium,isTermuxEnvironment} from '../bridge/whatsapp-secondary/chromium-discovery.js';
import {createBootstrapToken,createQrBootstrapServer,isPrivateNetworkAddress} from '../bridge/whatsapp-secondary/bootstrap-server.js';
import {resolveRuntimeConfig} from '../bridge/whatsapp-secondary/runtime-config.js';

const root=path.resolve('.'),read=relative=>readFile(path.join(root,relative),'utf8');

test('Termux usa runtime privado, health localhost y nunca shared storage',()=>{const env={HOME:'/data/data/com.termux/files/home',PREFIX:'/data/data/com.termux/files/usr',TERMUX_VERSION:'0.118.3',RADAR_BRIDGE_RUNTIME_DIR:'/data/data/com.termux/files/home/.radar-whatsapp-secondary'},config=resolveRuntimeConfig(env,'android');assert.equal(isTermuxEnvironment(env),true);assert.equal(config.healthHost,'127.0.0.1');assert.ok(config.runtimeRoot.startsWith(env.HOME));assert.equal(/sdcard|Download|Documents/.test(config.runtimeRoot),false);});

test('Chromium discovery prioriza env y detecta chromium-browser de Termux',async()=>{const env={PREFIX:'/data/data/com.termux/files/usr',CHROMIUM_PATH:'/private/custom-chromium'},seen=[];const found=await discoverChromium(env,{accessFn:async candidate=>{seen.push(candidate);if(candidate!=='/data/data/com.termux/files/usr/bin/chromium-browser')throw Object.assign(new Error(),{code:'ENOENT'});}});assert.equal(found,'/data/data/com.termux/files/usr/bin/chromium-browser');assert.equal(seen[0],'/private/custom-chromium');assert.ok(chromiumCandidates(env).includes('/data/data/com.termux/files/usr/bin/chromium'));});

test('bootstrap QR usa token aleatorio, LAN controlada, expira y desaparece',async()=>{const a=createBootstrapToken(),b=createBootstrapToken();assert.notEqual(a,b);assert.ok(a.length>=40);let now=1000;const bootstrap=createQrBootstrapServer({token:a,host:'127.0.0.1',port:0,ttlMs:300000,now:()=>now,renderQr:async()=>'<svg>SAFE_QR</svg>'});const address=await bootstrap.start(),url=`http://127.0.0.1:${address.port}/bootstrap/${a}`;assert.equal((await fetch(url)).status,202);bootstrap.setQr('never-log-this');const page=await fetch(url);assert.equal(page.status,200);assert.match(await page.text(),/SAFE_QR/);await bootstrap.invalidate();assert.equal(bootstrap.server.listening,false);const expired=createQrBootstrapServer({token:b,host:'127.0.0.1',port:0,ttlMs:10,now:()=>now,renderQr:async()=>'<svg/>'}),expiredAddress=await expired.start();now=2000;assert.equal((await fetch(`http://127.0.0.1:${expiredAddress.port}/bootstrap/${b}`)).status,404);await expired.stop();});

test('bootstrap acepta solo loopback/LAN y rechaza Internet público',()=>{for(const address of ['127.0.0.1','::1','::ffff:192.168.1.20','10.0.0.2','172.16.5.3','fd00::1'])assert.equal(isPrivateNetworkAddress(address),true);for(const address of ['8.8.8.8','1.1.1.1','2001:4860:4860::8888'])assert.equal(isPrivateNetworkAddress(address),false);});

test('scripts preparan config 600, wake lock, Boot, runit, restart y rotación',async()=>{const configure=await read('deploy/android-termux/configure.sh'),install=await read('deploy/android-termux/install.sh'),start=await read('deploy/android-termux/start.sh'),stop=await read('deploy/android-termux/stop.sh'),boot=await read('deploy/android-termux/termux-boot-start.sh'),service=await read('deploy/android-termux/service/run'),log=await read('deploy/android-termux/service/log-run');assert.match(configure,/chmod 600/);assert.match(install,/PUPPETEER_SKIP_DOWNLOAD=true npm ci/);assert.match(install,/pkg install -y x11-repo/);assert.match(start,/termux-wake-lock/);assert.match(stop,/termux-wake-unlock/);assert.match(boot,/start-services\.sh/);assert.match(service,/exec node index\.js/);assert.match(log,/s1000000/);assert.match(log,/n5/);for(const source of [configure,install,start,stop,boot,service,log])assert.equal(/\/sdcard|\/storage\/emulated|Download\//.test(source),false);});

test('installación es conceptualmente idempotente y no inicia WhatsApp/QR',async()=>{const install=await read('deploy/android-termux/install.sh');assert.match(install,/mkdir -p/);assert.match(install,/pkg install -y/);assert.equal(/node index\.js|bootstrap-qr\.sh|RADAR_BRIDGE_MODE=live/.test(install),false);});

test('diagnóstico no consulta identificadores sensibles ni IP pública',async()=>{const diagnostic=await read('deploy/android-termux/device-diagnostic.sh');for(const forbidden of ['imei','android_id','serialno','contacts','ifconfig.me','ipinfo.io'])assert.equal(diagnostic.toLowerCase().includes(forbidden),false);});

test('bootstrap no registra QR y health/metrics conservan privacidad',async()=>{const bootstrap=await read('bridge/whatsapp-secondary/bootstrap-server.js'),health=await read('bridge/whatsapp-secondary/health-server.js'),index=await read('bridge/whatsapp-secondary/index.js');assert.equal(/logger\([^\n]*qrValue|console\.log\([^\n]*qr/i.test(bootstrap+index),false);for(const forbidden of ['groupId','authorId','authorPhone','messageText','RADAR_BRIDGE_INGEST_TOKEN'])assert.equal(health.includes(forbidden),false);});

test('Android mantiene read-only, grupos y política iPhone V0.6.2',async()=>{const sources=(await Promise.all(['bridge/whatsapp-secondary/index.js','bridge/whatsapp-secondary/bridge.js','bridge/whatsapp-secondary/event-normalizer.js'].map(read))).join('\n');for(const api of ['sendMessage(','reply(','react(','forward(','createGroup(','addParticipants(','removeParticipants(','promoteParticipants(','demoteParticipants('])assert.equal(sources.includes(api),false);const app=await read('app.js');assert.match(app,/SECONDARY_POLL_MS/);assert.match(app,/visibilitychange/);assert.match(app,/viewImport/);});
