import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { openIndexedDatabase, readStoreCounts } from '../idb-open.js';

function requestApi(sequence){let calls=0;return {get calls(){return calls},open(){const req={};const step=sequence[calls++]||{};queueMicrotask(()=>{if(step.hang)return;if(step.blocked)req.onblocked?.();if(step.error){req.error=step.error;req.onerror?.();return;}req.result=step.db||{close(){this.closed=true}};req.onsuccess?.();});return req;}}}
const instant=()=>Promise.resolve();

test('open exitoso configura versionchange',async()=>{const db={closed:false,close(){this.closed=true}};const api=requestApi([{db}]);assert.equal(await openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,delay:instant}),db);db.onversionchange();assert.equal(db.closed,true)});
test('UnknownError reintenta y abre',async()=>{const api=requestApi([{error:Object.assign(new Error('temporal'),{name:'UnknownError'})},{}]);await openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,delay:instant});assert.equal(api.calls,2)});
test('internal Indexed Database server reintenta',async()=>{const api=requestApi([{error:new Error('An internal error was encountered in the Indexed Database server')},{}]);await openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,delay:instant});assert.equal(api.calls,2)});
test('open colgado vence timeout y limita tres intentos',async()=>{const api=requestApi([{hang:true},{hang:true},{hang:true}]);await assert.rejects(openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,timeoutMs:5,delay:instant}),e=>e.name==='TimeoutError'&&e.attempt===3);assert.equal(api.calls,3)});
test('onsuccess tardío cierra la conexión',async()=>{let req,closed=false;const api={open(){req={};return req}};const promise=openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,timeoutMs:5,maxAttempts:1});await assert.rejects(promise);req.result={close(){closed=true}};req.onsuccess();assert.equal(closed,true)});
test('onblocked emite diagnóstico',async()=>{const events=[];const api=requestApi([{blocked:true}]);await openIndexedDatabase({indexedDBApi:api,name:'grupos-inmobiliarios',version:15,onDiagnostic:e=>events.push(e),delay:instant});assert(events.some(e=>e.status==='blocked'&&e.attempt===1))});
test('probe cuenta properties e imports existentes',async()=>{const fakeReq=value=>{const r={result:value};queueMicrotask(()=>r.onsuccess?.());return r};const db={transaction(names,mode){assert.deepEqual(names,['properties','imports']);assert.equal(mode,'readonly');return {objectStore:n=>({count:()=>fakeReq(n==='properties'?7:3)})}}};assert.deepEqual(await readStoreCounts(db,{properties:'properties',imports:'imports'}),{properties:7,imports:3})});
test('nunca hay recuperación destructiva',()=>{const db=fs.readFileSync(new URL('../db.js',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),helper=fs.readFileSync(new URL('../idb-open.js',import.meta.url),'utf8');const recovery=helper+db.slice(db.indexOf('export function openDB'),db.indexOf('function reqP'))+app.slice(app.indexOf('let startupBuildSha'),app.indexOf('setInterval'));assert.doesNotMatch(recovery,/deleteDatabase\s*\(/);assert.doesNotMatch(recovery,/objectStore\([^)]*\)\.clear\s*\(/)});
test('fallo location conserva ruta de inventario',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(source,/catch\(error\)\{locationFailed=true/);assert.match(source,/loadData\(\{skipLocation:locationFailed\}\)/);assert.match(source,/if\(!skipLocation&&/)});
test('fallo externo no bloquea core',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(source,/await initCore\(\)/);assert.match(source,/initExternalServices\(\)\.catch/);assert.ok(source.indexOf('await initCore()')<source.indexOf('initExternalServices().catch'))});
