import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function outreach(text){const original=String(text||'').trim();return ['Hola colega, esta propiedad sigue disponible:','',original||'Propiedad consultada en Radar Inmobiliario.','','Quedo atenta, gracias.'].join('\n');}
test('WhatsApp usa encabezado, p.text completo y cierre exactos',()=>{const original='ÿ¡ CASA EN VENTA\n3 habitaciones\nPrecio: 75.000$';const message=outreach(original);assert.ok(message.includes('Hola colega, esta propiedad sigue disponible:'));assert.ok(message.includes(original));assert.ok(message.endsWith('Quedo atenta, gracias.'));assert.match(app,/const original=String\(p\?\.text\|\|''\)\.trim\(\)/);assert.equal((app.match(/buildWhatsAppHref\(p\)/g)||[]).length>=3,true);});
test('limpiar filtros vacÃ­a controles, Sets y las tres claves persistidas',()=>{const block=app.slice(app.indexOf("$('#clearFilters').onclick"),app.indexOf('const PROPERTY_TYPES'));for(const id of ['operation','residence','minPrice','maxPrice','bedrooms','bathrooms','parking','minArea','maxArea','maxAge'])assert.ok(block.includes(id));for(const id of ['planta100','planta','pozo','tanque','amoblado','financiamiento','piscina','onlyPhone'])assert.ok(block.includes(id));for(const set of ['selectedPropertyTypes','selectedMunicipalities','selectedZones'])assert.match(block,new RegExp(set+'\\.clear\\(\\)'));for(const key of ['SEARCH_STATE_KEY','SEARCH_SCROLL_KEY','SEARCH_CARD_KEY'])assert.ok(block.includes(key));assert.match(block,/sessionStorage\.removeItem/);assert.match(block,/runSearch\(true,\{persist:false\}\)/);});
test('confirmar selector mÃºltiple provoca bÃºsqueda y persistencia',()=>{const block=app.slice(app.indexOf("$('#selectorApplyBtn').onclick"),app.indexOf('async function openDetail'));assert.match(block,/updateSelectorUI\(\)/);assert.match(block,/multiSelectorDialog'\)\.close\(\)/);assert.match(block,/runSearch\(\)/);});
test('eliminar una pill actualiza bÃºsqueda y elimina el valor del Set',()=>{const block=app.slice(app.indexOf('function renderPills'),app.indexOf('function updateSelectorUI'));assert.match(block,/set\.delete\(b\.dataset\.value\)/);assert.match(block,/updateSelectorUI\(\)/);assert.match(block,/runSearch\(\)/);});
test('controles mÃ³viles tienen listeners inmediatos o con debounce',()=>{for(const id of ['operation','bedrooms','bathrooms','parking','maxAge','sortMode','planta100','planta','pozo','tanque','amoblado','financiamiento','piscina','onlyPhone','residence','minPrice','maxPrice','minArea','maxArea'])assert.ok(app.includes("'"+id+"'"));assert.match(app,/scheduleFilterSearch/);});
