import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PUBLIC_PROPERTY_FIELDS,serializePublicProperty} from '../core/radar/own-listings.js';
import {RadarCoreFoundation} from '../core/radar/foundation.js';
import {processSecondaryEvents,resolveSecondaryAttachmentSource} from '../ingestion/secondary-processing.js';
import {planLegacyMasterArchive} from '../db.js';

test('public serializer usa allowlist y unknown field es privado por defecto',()=>{const input={id:'p',price_usd:90000,commission_pct:5,owner_phone:'58412',future_private_secret:'DO_NOT_LEAK',source_messages:[{raw_text:'private'}]},output=serializePublicProperty(input);assert.deepEqual(output,{id:'p',price_usd:90000});assert.ok(PUBLIC_PROPERTY_FIELDS.includes('price_usd'));assert.equal('future_private_secret'in output,false);});

test('attachment separa external WhatsApp ID del UUID interno y recorre provenance',async()=>{const core=new RadarCoreFoundation(),channel=core.createChannel({channel_type:'WHATSAPP_SECONDARY',account_role:'SECONDARY_NUMBER'}),thread=core.upsertThread({ingestion_channel_id:channel.id,external_thread_id:'120@g.us'}),message=(await core.receiveSourceMessage({source_thread_id:thread.id,ingestion_channel_id:channel.id,external_message_id:'wa-msg-123',raw_text:'Apartamento con foto',received_at:'2026-08-27T12:00:00Z'})).message,result=processSecondaryEvents([{messageId:'wa-msg-123',groupId:'120@g.us',groupName:'Grupo',authorId:'584121234567@c.us',timestamp:'2026-08-27T12:00:00Z',receivedAt:'2026-08-27T12:00:00Z',messageType:'image',text:'Apartamento en venta Trigal Norte precio $80.000',hasMedia:true,mediaType:'image'}]),resolved=resolveSecondaryAttachmentSource(result.attachments[0],message);assert.equal(resolved.source_message_id,message.id);assert.equal(resolved.external_message_id,'wa-msg-123');assert.equal(resolved.external_media_id,'wa-msg-123');assert.equal(core.messages.get(resolved.source_message_id).source_thread_id,thread.id);assert.equal(core.threads.get(thread.id).ingestion_channel_id,channel.id);});

test('attachment contract impide confundir external ID con source_message_id interno',()=>{const attachment={external_message_id:'wa-msg-123',external_media_id:'wa-msg-123',source_message_id:null,provenance_status:'UNRESOLVED'};assert.throws(()=>resolveSecondaryAttachmentSource(attachment,{id:'wa-msg-123',external_message_id:'wa-msg-123'}),/uuid/);});

test('SQL conserva FK interno y estado unresolved explícito',async()=>{const sql=await readFile(new URL('../db/migrations/002_phase_0b_identity_media_own.sql',import.meta.url),'utf8'),adapter=await readFile(new URL('../ingestion/secondary-processing.js',import.meta.url),'utf8');assert.match(sql,/source_message_id uuid REFERENCES source_messages\(id\)/i);assert.match(sql,/external_message_id text/i);assert.match(sql,/provenance_status='UNRESOLVED'[\s\S]*source_message_id IS NULL/i);assert.doesNotMatch(adapter,/source_message_id:event\.messageId/);});

test('merge legacy archiva, redirige y conserva todas las fuentes/legacy IDs',()=>{const a={id:'A',status:'active',legacy_ids:['l1']},b={id:'B',status:'active',legacy_ids:['l2']},posts=[{id:'s1',master_id:'A'},{id:'s2',master_id:'B'}],plan=planLegacyMasterArchive(a,b,posts,'2026-08-27T00:00:00Z');assert.equal(plan.canonical.id,'A');assert.deepEqual(plan.canonical.legacy_ids,['l1','l2']);assert.equal(plan.archived.status,'ARCHIVED');assert.equal(plan.archived.redirected_to,'A');assert.deepEqual(plan.redirect,{old_property_id:'B',canonical_property_id:'A',merged_at:'2026-08-27T00:00:00Z',reason:'legacy_core_consolidation',decision_reference:null});assert.equal(plan.sources.length,2);assert.ok(plan.sources.every(x=>x.master_id==='A'));});

test('syncRadarCore no contiene eliminación física de masters',async()=>{const source=await readFile(new URL('../db.js',import.meta.url),'utf8'),body=source.slice(source.indexOf('export async function syncRadarCore'),source.indexOf('export async function getRadarCoreStats'));assert.doesNotMatch(body,/\bms\.delete\s*\(/);assert.match(body,/PROPERTY_REDIRECT_STORE/);assert.match(body,/planLegacyMasterArchive/);assert.match(source,/archived:\{\.\.\.duplicate,status:'ARCHIVED'/);});
