import test from 'node:test';
import assert from 'node:assert/strict';
import {assessOpportunity,buildClientPackage,reconcileReadiness} from '../core/radar/readiness-engine.js';

const NOW=Date.parse('2026-08-28T12:00:00Z'),opp=(id,pid)=>({id,property_id:pid,status:'ACTIVE'}),authorized=pid=>({mediaAssets:[{id:`m-${pid}`,rights_status:'AUTHORIZED',storage_key:'PRIVATE/STORAGE'}],propertyMedia:[{property_id:pid,media_asset_id:`m-${pid}`,client_allowed:true}]});
const base=(id,extra={})=>({id,territory_id:'trigal',operation:'SALE',property_type:'Casa',price_usd:60000,area_m2:100,bedrooms:3,bathrooms:2,status:'ACTIVE',availability_status:'verified',last_verified_at:'2026-08-27T00:00:00Z',...extra});

test('Casa without territory is NEEDS_FACTS',()=>{assert.equal(assessOpportunity({opportunity:opp('o1','p1'),property:base('p1',{territory_id:null}),...authorized('p1'),now:NOW}).assessment.status,'NEEDS_FACTS');});
test('Casa missing area bedrooms bathrooms is NEEDS_FACTS',()=>{const out=assessOpportunity({opportunity:opp('o2','p2'),property:base('p2',{area_m2:null,bedrooms:null,bathrooms:null}),...authorized('p2'),now:NOW});assert.equal(out.assessment.status,'NEEDS_FACTS');assert.deepEqual(out.assessment.gaps,['area','bedrooms','bathrooms']);});
test('Terreno with area can be READY without residential rooms',()=>{assert.equal(assessOpportunity({opportunity:opp('o3','p3'),property:base('p3',{property_type:'Terreno',bedrooms:null,bathrooms:null}),...authorized('p3'),now:NOW}).assessment.status,'READY');});
test('two active real source prices conflict',()=>{const p=base('p4'),sourcePosts=[{master_id:'p4',observed_price:60000,published_at:'2026-08-27T00:00:00Z'},{master_id:'p4',observed_price:65000,published_at:'2026-08-27T00:00:00Z'}];assert.equal(assessOpportunity({opportunity:opp('o4','p4'),property:p,sourcePosts,...authorized('p4'),now:NOW}).assessment.status,'PRICE_CONFLICT');});
test('inactive historical source price does not create false conflict',()=>{const p=base('p5'),sourcePosts=[{master_id:'p5',observed_price:60000,published_at:'2026-08-27T00:00:00Z'},{master_id:'p5',observed_price:50000,is_historical:true,published_at:'2026-08-01T00:00:00Z'}];assert.equal(assessOpportunity({opportunity:opp('o5','p5'),property:p,sourcePosts,...authorized('p5'),now:NOW}).assessment.status,'READY');});
test('client payload excludes storage locator',()=>{const p=base('p6'),o=opp('o6','p6'),m=authorized('p6'),assessment=assessOpportunity({opportunity:o,property:p,...m,now:NOW}).assessment,built=buildClientPackage({opportunity:o,property:p,assessment,...m,now:NOW});assert.equal(JSON.stringify(built.package.payload_json).includes('storage_key'),false);assert.equal(JSON.stringify(built.package.payload_json).includes('PRIVATE/STORAGE'),false);assert.equal(built.media[0].media_asset_id,'m-p6');});
test('revoked media disappears from client package and targeted scope remains narrow',()=>{const p=base('p7'),o=opp('o7','p7'),m=authorized('p7'),first=reconcileReadiness({opportunities:[o,opp('other','other')],properties:[p,base('other')],...m,scope:{propertyIds:['p7']},now:NOW});m.mediaAssets[0].rights_status='UNKNOWN';const second=reconcileReadiness({opportunities:[o],properties:[p],...m,scope:{propertyIds:['p7']},now:NOW+1000});assert.equal(first.packageMedia.length,1);assert.equal(second.packageMedia.length,0);assert.equal(second.evaluated,1);assert.equal(second.assessments[0].status,'RIGHTS_REVIEW');});
