import {runOpportunityReadiness,getReadinessAssessments,getEnrichmentTasks,getPropertyPackages,getPackageMedia,exportDatabaseSnapshot} from '../db.js';
import {APP_LABEL} from '../version.js';

const DB='grupos-inmobiliarios',VERSION=10,STATE='phase-0d-e2e-state',result=document.querySelector('#result'),NOW=Date.parse('2026-08-28T12:00:00Z');
const assert=(v,m)=>{if(!v)throw new Error(m);},done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});
const open=()=>new Promise((resolve,reject)=>{const req=indexedDB.open(DB,VERSION);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
const prop=(id,extra={})=>({id,workspace_id:'local',operation:'Venta',property_type:'Casa',price_usd:55000,status:'ACTIVE',availability_status:'verified',last_verified_at:'2026-08-27T12:00:00Z',last_seen_at:'2026-08-27T12:00:00Z',commission_pct:5,owner_phone:'PRIVATE-0412',internal_notes:'PRIVATE-NOTE',...extra});
const opp=id=>({id:`TEST-0D-O${id}`,workspace_id:'local',demand_id:`TEST-0D-D${id}`,property_id:`TEST-0D-P${id}`,opportunity_type:'CLIENT_PROPERTY',status:'ACTIVE',created_at:new Date(NOW).toISOString(),updated_at:new Date(NOW).toISOString()});
async function seed(){await getReadinessAssessments();const db=await open();assert(db.version===10,'IndexedDB no abrió V10');for(const name of ['readiness_assessments','enrichment_tasks','property_packages','package_media'])assert(db.objectStoreNames.contains(name),`Falta ${name}`);const tx=db.transaction(['master_properties','opportunities','media_assets','property_media'],'readwrite');for(const id of [1,2,3,4])tx.objectStore('opportunities').put(opp(id));tx.objectStore('master_properties').put(prop('TEST-0D-P1'));tx.objectStore('master_properties').put(prop('TEST-0D-P2'));tx.objectStore('master_properties').put(prop('TEST-0D-P3',{price_conflict:true}));tx.objectStore('master_properties').put(prop('TEST-0D-P4',{availability_status:'unverified',last_verified_at:null,last_seen_at:'2026-07-01T00:00:00Z'}));tx.objectStore('media_assets').put({id:'TEST-0D-M1',workspace_id:'local',rights_status:'AUTHORIZED',storage_key:'media/test-p1.jpg',mime_type:'image/jpeg'});tx.objectStore('property_media').put({id:'TEST-0D-PM1',property_id:'TEST-0D-P1',media_asset_id:'TEST-0D-M1',client_allowed:true,is_primary:true});await done(tx);db.close();await runOpportunityReadiness({full:true,now:NOW});}
async function addP2Media(){const db=await open(),tx=db.transaction(['media_assets','property_media'],'readwrite');tx.objectStore('media_assets').put({id:'TEST-0D-M2',workspace_id:'local',rights_status:'AUTHORIZED',storage_key:'media/test-p2.jpg',mime_type:'image/jpeg'});tx.objectStore('property_media').put({id:'TEST-0D-PM2',property_id:'TEST-0D-P2',media_asset_id:'TEST-0D-M2',client_allowed:true});await done(tx);db.close();}
async function run(){const phase=sessionStorage.getItem(STATE)||'seed';if(phase==='seed'){await seed();const a=await getReadinessAssessments(),t=await getEnrichmentTasks();assert(a.find(x=>x.property_id==='TEST-0D-P1')?.status==='READY','P1 no quedó READY');assert(a.find(x=>x.property_id==='TEST-0D-P2')?.status==='NEEDS_MEDIA','P2 no quedó NEEDS_MEDIA');assert(t.some(x=>x.property_id==='TEST-0D-P2'&&x.task_type==='FIND_MEDIA'),'P2 no creó FIND_MEDIA');assert(a.find(x=>x.property_id==='TEST-0D-P3')?.status==='PRICE_CONFLICT','P3 no detectó conflicto');assert(t.some(x=>x.property_id==='TEST-0D-P3'&&x.task_type==='VERIFY_PRICE'),'P3 no creó VERIFY_PRICE');assert(a.find(x=>x.property_id==='TEST-0D-P4')?.status==='VERIFY_AVAILABILITY','P4 no pidió vigencia');await addP2Media();await runOpportunityReadiness({propertyIds:['TEST-0D-P2'],now:NOW+1000});sessionStorage.setItem(STATE,'reload');location.reload();return;}const assessments=await getReadinessAssessments(),tasks=await getEnrichmentTasks(),packages=await getPropertyPackages(),packageMedia=await getPackageMedia(),backup=await exportDatabaseSnapshot();assert(assessments.find(x=>x.property_id==='TEST-0D-P2')?.status==='READY','P2 no persistió READY tras reload');assert(tasks.filter(x=>x.property_id==='TEST-0D-P2'&&x.task_type==='FIND_MEDIA').length===1,'Tarea duplicada');assert(packages.filter(x=>x.property_id==='TEST-0D-P2').length===1,'Package duplicado');assert(packageMedia.filter(x=>x.package_id==='package_TEST-0D-O2').length===1,'Media package duplicada');assert(assessments.find(x=>x.property_id==='TEST-0D-P1')?.status==='READY','Reevaluación dirigida alteró P1');const raw=JSON.stringify(packages);for(const secret of ['commission','owner_phone','PRIVATE-0412','PRIVATE-NOTE','own_listing_details'])assert(!raw.includes(secret),`Fuga privada: ${secret}`);for(const store of ['readiness_assessments','enrichment_tasks','property_packages','package_media'])assert(Array.isArray(backup.stores[store]),`Backup omite ${store}`);sessionStorage.removeItem(STATE);result.textContent=JSON.stringify({status:'PASS',indexedDBVersion:10,P1:'READY',P2:'NEEDS_MEDIA -> READY',P3:'PRICE_CONFLICT',P4:'VERIFY_AVAILABILITY',idempotency:'PASS',privacy:'PASS',targetedReevaluation:'PASS',backupSchema:backup.schemaVersion,versionLabel:APP_LABEL},null,2);}
run().catch(error=>{sessionStorage.removeItem(STATE);document.body.dataset.status='FAIL';result.textContent=`FAIL\n${error.stack||error.message}`;});
