import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {CandidateIndex,PropertyIdentityEngine,priceConflict,IDENTITY_MODEL_VERSION} from '../core/radar/identity-engine.js';
import {PropertyIdentityService,ingestMessageWithOptionalMedia} from '../core/radar/identity-service.js';
import {differenceHash,perceptualDistance,MediaFoundation} from '../core/radar/media-foundation.js';
import {InMemoryMediaStorage} from '../core/radar/media-storage.js';
import {OwnListingRegistry,serializePublicProperty} from '../core/radar/own-listings.js';
import {radarIdentityMediaEnabled} from '../core/radar/config.js';
import {RadarCoreFoundation} from '../core/radar/foundation.js';
import {migrateBackupSnapshot,BACKUP_STORE_NAMES} from '../db.js';
import {processSecondaryEvents} from '../ingestion/secondary-processing.js';

const candidate=(overrides={})=>({id:'p1',territory_id:'trigal-norte',property_type:'apartamento',operation:'venta',residence_name:'Residencias Sol',area_m2:144,bedrooms:3,bathrooms:2,parking:2,price_usd:130000,...overrides});
const source=(overrides={})=>({territory_id:'trigal-norte',property_type:'apartamento',operation:'venta',residence_name:'Residencias Sol',area_m2:145,bedrooms:3,bathrooms:2,parking:2,price_usd:132000,...overrides});

test('I1 mismo source exacto reintentado no duplica',async()=>{const core=new RadarCoreFoundation(),ch=core.createChannel({channel_type:'WHATSAPP_ZIP',account_role:'PRIMARY_NUMBER'}),th=core.upsertThread({ingestion_channel_id:ch.id,external_thread_id:'g'}),input={source_thread_id:th.id,ingestion_channel_id:ch.id,external_message_id:'m1',raw_text:'Apartamento',received_at:'2026-08-27T00:00:00Z'};assert.equal((await core.receiveSourceMessage(input)).duplicate,false);assert.equal((await core.receiveSourceMessage(input)).duplicate,true);assert.equal(core.messages.size,1);});

test('I2 ZIP + secondary convergen en un Master con dos sources',async()=>{const core=new RadarCoreFoundation(),zip=core.createChannel({channel_type:'WHATSAPP_ZIP'}),sec=core.createChannel({channel_type:'WHATSAPP_SECONDARY'}),zt=core.upsertThread({ingestion_channel_id:zip.id,external_thread_id:'z'}),st=core.upsertThread({ingestion_channel_id:sec.id,external_thread_id:'s'}),m1=(await core.receiveSourceMessage({source_thread_id:zt.id,ingestion_channel_id:zip.id,external_message_id:'z1',raw_text:'A',received_at:'2026-08-27T00:00:00Z'})).message,m2=(await core.receiveSourceMessage({source_thread_id:st.id,ingestion_channel_id:sec.id,external_message_id:'s1',raw_text:'B',received_at:'2026-08-27T00:01:00Z'})).message;const first=core.createOrLinkProperty({identity_key:'initial',fields:candidate(),source_message_id:m1.id});const service=new PropertyIdentityService({foundation:core});service.indexProperty({...first.property,external_property_code:'REMAX-778'});const result=service.ingestDecision(source({external_property_code:'REMAX-778'}),{source_message_id:m2.id,identity_key:'second',fields:source()});assert.equal(result.decision,'AUTO_LINK');assert.equal(core.properties.size,1);assert.equal(core.propertySources.size,2);});

test('I3 cinco corredores producen un Master y cinco sources',async()=>{const core=new RadarCoreFoundation(),ch=core.createChannel({channel_type:'MANUAL'}),th=core.upsertThread({ingestion_channel_id:ch.id,external_thread_id:'brokers'}),service=new PropertyIdentityService({foundation:core});for(let i=0;i<5;i++){const m=(await core.receiveSourceMessage({source_thread_id:th.id,ingestion_channel_id:ch.id,external_message_id:`m${i}`,raw_text:`broker ${i}`,received_at:`2026-08-27T00:0${i}:00Z`})).message;if(i===0){const first=core.createOrLinkProperty({identity_key:'first',fields:candidate(),source_message_id:m.id});service.indexProperty({...first.property,external_property_code:'CODE-5'});}else service.ingestDecision(source({external_property_code:'CODE-5'}),{source_message_id:m.id,identity_key:`new-${i}`,fields:source()});}assert.equal(core.properties.size,1);assert.equal(core.propertySources.size,5);});

test('I4 misma zona precio y tipo no auto-merge',()=>{const result=new PropertyIdentityEngine().evaluate({territory_id:'t',property_type:'apartamento',price_usd:90000},candidate({territory_id:'t',price_usd:90000,residence_name:null,area_m2:null,bedrooms:null,bathrooms:null,parking:null}));assert.notEqual(result.band,'AUTO_LINK');});
test('I5 130k vs 70k sin identidad fuerte no auto-link',()=>{const result=new PropertyIdentityEngine().evaluate({territory_id:'t',property_type:'apartamento',price_usd:70000},candidate({territory_id:'t',price_usd:130000,residence_name:null,area_m2:null,bedrooms:null,bathrooms:null,parking:null}));assert.equal(result.band,'KEEP_SEPARATE');assert.equal(result.price_conflict.band,'EXTREME');});
test('I6 listing ID fiable con precio extremo manda review y no cambia canon',()=>{const master=candidate({source_type:'portal',external_listing_id:'A-1',price_usd:130000}),result=new PropertyIdentityEngine().evaluate(source({source_type:'portal',external_listing_id:'A-1',price_usd:70000}),master);assert.equal(result.band,'REVIEW');assert.equal(master.price_usd,130000);assert.ok(result.conflicts.includes('price_extreme'));});
test('I7 SHA exacto + estructura compatible es identidad fuerte',()=>{const result=new PropertyIdentityEngine().evaluate(source({image_sha256:'abc'}),candidate({image_sha256:'abc'}));assert.equal(result.band,'AUTO_LINK');assert.ok(result.strong.includes('same_image_sha256'));});
test('I8 pHash similar aislado nunca auto-merge',()=>{const result=new PropertyIdentityEngine().evaluate({phash_distance:2},candidate({territory_id:null,property_type:null,residence_name:null,area_m2:null,bedrooms:null,bathrooms:null,parking:null}));assert.notEqual(result.band,'AUTO_LINK');});
test('I9 territorio incompatible bloquea auto-link y manda review',()=>{const result=new PropertyIdentityEngine().evaluate(source({territory_id:'otro',external_property_code:'X'}),candidate({external_property_code:'X'}));assert.equal(result.band,'REVIEW');assert.ok(result.conflicts.includes('incompatible_territory'));});
test('I10 dato ausente no se completa desde candidato para subir score',()=>{const result=new PropertyIdentityEngine().evaluate({territory_id:'trigal-norte'},candidate());assert.equal(result.compatible.length,1);assert.ok(result.score<0.42);});
test('candidate generation usa bloques, no full scan',()=>{const index=new CandidateIndex();index.add(candidate({id:'a',territory_id:'t1'}));index.add(candidate({id:'b',territory_id:'t2',residence_name:'Otro'}));assert.deepEqual(index.candidates({territory_id:'t1',property_type:'apartamento'}).map(x=>x.id),['a']);});
test('price conflict policy conserva bandas',()=>{assert.equal(priceConflict(100,108).band,'COMPATIBLE');assert.equal(priceConflict(100,120).band,'MODERATE');assert.equal(priceConflict(100,140).band,'IMPORTANT');assert.equal(priceConflict(100,160).band,'STRONG');assert.equal(priceConflict(100,170).band,'EXTREME');});

test('M1/M2 dos attachments idénticos conservan SHA y deduplican asset',async()=>{const media=new MediaFoundation({workspaceId:'w',storage:new InMemoryMediaStorage()}),a=media.receiveAttachment({source_message_id:'m1',media_type:'IMAGE'}),b=media.receiveAttachment({source_message_id:'m2',media_type:'IMAGE'}),bytes=new TextEncoder().encode('same-image');const x=await media.ingestBytes(a.id,bytes,{media_role:'PHOTO'}),y=await media.ingestBytes(b.id,bytes,{media_role:'PHOTO'});assert.equal(media.attachments.size,2);assert.equal(media.assets.size,1);assert.equal(x.asset.sha256,y.asset.sha256);assert.equal(y.deduplicated,true);});
test('M3 imagen recomprimida/redimensionada conserva dHash razonablemente similar',()=>{const original=Uint8Array.from({length:72},(_,i)=>(i%9)*20+Math.floor(i/9)),changed=Uint8Array.from(original,(v,i)=>Math.max(0,Math.min(255,v+(i%7===0?3:-2)))),a=differenceHash(original),b=differenceHash(changed);assert.ok(perceptualDistance(a,b)<=10);});
test('M5 fallo storage no pierde mensaje ni hechos',async()=>{let failed=false;const result=await ingestMessageWithOptionalMedia({saveMessage:async()=>({id:'m'}),saveFacts:async()=>[{field:'price'}],mediaWork:async()=>{throw new Error('storage down');},markAttachmentFailed:()=>{failed=true;}},{});assert.equal(result.message.id,'m');assert.equal(result.facts.length,1);assert.equal(result.media.status,'FAILED');assert.equal(failed,true);});
test('secondary media metadata crea attachment OBSERVED sin descargar ni bloquear texto',()=>{const at='2026-08-27T12:00:00Z',result=processSecondaryEvents([{messageId:'img1',groupId:'120@g.us',groupName:'Grupo',authorId:'584121234567@c.us',timestamp:at,receivedAt:at,messageType:'image',text:'Apartamento en venta Trigal Norte precio $80.000',hasMedia:true,mediaType:'image'}]);assert.equal(result.records.length,1);assert.equal(result.attachments.length,1);assert.equal(result.attachments[0].media_status,'OBSERVED');assert.equal(result.attachments[0].storage_locator,null);});
test('M6-M8 derechos controlan client_allowed explícito',async()=>{for(const rights of ['UNKNOWN','INTERNAL_ONLY']){const media=new MediaFoundation({workspaceId:'w',storage:new InMemoryMediaStorage()}),a=media.receiveAttachment({source_message_id:'m',media_type:'IMAGE'}),{asset}=await media.ingestBytes(a.id,new TextEncoder().encode(rights),{rights_status:rights});assert.throws(()=>media.linkProperty({property_id:'p',media_asset_id:asset.id,client_allowed:true}),/rights/);}const media=new MediaFoundation({workspaceId:'w',storage:new InMemoryMediaStorage()}),a=media.receiveAttachment({source_message_id:'m',media_type:'IMAGE'}),{asset}=await media.ingestBytes(a.id,new TextEncoder().encode('owned'),{rights_status:'OWNED'});assert.equal(media.linkProperty({property_id:'p',media_asset_id:asset.id,source_attachment_id:a.id,client_allowed:true}).client_allowed,true);});
test('M9 provenance recupera attachment y asset',async()=>{const media=new MediaFoundation({workspaceId:'w',storage:new InMemoryMediaStorage()}),a=media.receiveAttachment({source_message_id:'m',media_type:'IMAGE',metadata_json:{thread:'g'}}),{asset}=await media.ingestBytes(a.id,new TextEncoder().encode('photo'));media.linkProperty({property_id:'p',media_asset_id:asset.id,source_attachment_id:a.id});assert.equal(media.provenance(asset.id)[0].attachment.source_message_id,'m');});

test('O1/O2 OWN y MARKET requieren confirmación y conservan historia',()=>{const events=[],registry=new OwnListingRegistry({eventSink:e=>events.push(e)}),p={id:'p',workspace_id:'w',ownership_scope:'UNKNOWN'};registry.setOwnership(p,'OWN',{actor_id:'u',provenance:'USER_CONFIRMED'});registry.saveDetails(p,{commission_pct:5,internal_notes:'privado'});registry.setOwnership(p,'MARKET',{actor_id:'u',provenance:'USER_CONFIRMED'});assert.equal(p.ownership_scope,'MARKET');assert.equal(events.length,2);assert.equal(registry.details.get('p').commission_pct,5);});
test('O3 publisher no convierte automáticamente a OWN',()=>{const p={id:'p',publisher_phone:'58412',ownership_scope:'UNKNOWN'};assert.equal(p.ownership_scope,'UNKNOWN');assert.throws(()=>new OwnListingRegistry().setOwnership(p,'OWN',{provenance:'INFERRED_PHONE'}),/confirmation/);});
test('O4/O5 serializer público excluye detalles y comisión',()=>{const output=serializePublicProperty({id:'p',price_usd:1,commission_pct:5,internal_notes:'x',own_listing_details:{agreement_type:'EXCLUSIVE'}});assert.deepEqual(output,{id:'p',price_usd:1});});
test('O6 backup V2 migra con stores 0B vacíos sin perder inventario',()=>{const old={format:'radar-inmobiliario-backup',backup_version:2,schemaVersion:2,stores:{properties:[{id:'p'}],master_properties:[{id:'m'}]}};const migrated=migrateBackupSnapshot(old);assert.equal(migrated.stores.properties.length,1);assert.equal(migrated.stores.master_properties.length,1);for(const name of ['source_attachments','media_assets','property_media','property_identity_links','property_redirects','own_listing_details','review_queue'])assert.deepEqual(migrated.stores[name],[]);assert.ok(BACKUP_STORE_NAMES.includes('own_listing_details'));});
test('merge de masters exige decisión, archiva origen y preserva lineage',async()=>{const core=new RadarCoreFoundation(),ch=core.createChannel({channel_type:'MANUAL'}),th=core.upsertThread({ingestion_channel_id:ch.id,external_thread_id:'g'}),m1=(await core.receiveSourceMessage({source_thread_id:th.id,ingestion_channel_id:ch.id,external_message_id:'1',raw_text:'a'})).message,m2=(await core.receiveSourceMessage({source_thread_id:th.id,ingestion_channel_id:ch.id,external_message_id:'2',raw_text:'b'})).message,a=core.createOrLinkProperty({identity_key:'a',fields:{},source_message_id:m1.id}).property,b=core.createOrLinkProperty({identity_key:'b',fields:{},source_message_id:m2.id}).property,fact=core.observeFact({source_message_id:m1.id,entity_type:'master_property',entity_id:a.id,field_key:'bedrooms',value_json:3}),media=new MediaFoundation({workspaceId:core.workspaceId,storage:new InMemoryMediaStorage()}),att=media.receiveAttachment({source_message_id:m1.id,media_type:'IMAGE'}),asset=(await media.ingestBytes(att.id,new TextEncoder().encode('merge-photo'))).asset;core.selectCanonicalFact({property_id:a.id,field_key:'bedrooms',evidence_fact_id:fact.fact.id});media.linkProperty({property_id:a.id,media_asset_id:asset.id,source_attachment_id:att.id});const service=new PropertyIdentityService({foundation:core,mediaFoundation:media});assert.throws(()=>service.mergePropertyMasters(a.id,b.id,{}),/human/);const merged=service.mergePropertyMasters(a.id,b.id,{decisionReference:'d',actorId:'u'});assert.equal(a.status,'ARCHIVED');assert.equal(merged.redirect.canonical_property_id,b.id);assert.equal([...core.propertySources.values()].filter(x=>x.property_id===b.id).length,2);assert.equal(fact.fact.entity_id,b.id);assert.ok(core.canonicalFacts.has(`${b.id}:bedrooms`));assert.equal([...media.propertyMedia.values()][0].property_id,b.id);});
test('feature flag identidad/media está OFF por defecto y versionada',()=>{assert.equal(radarIdentityMediaEnabled({}),false);assert.equal(radarIdentityMediaEnabled({RADAR_IDENTITY_MEDIA_ENABLED:'true'}),true);assert.equal(IDENTITY_MODEL_VERSION,'identity-v1');});
test('migración SQL 002 es aditiva, transaccional e indexada',async()=>{const sql=await readFile(new URL('../db/migrations/002_phase_0b_identity_media_own.sql',import.meta.url),'utf8');assert.match(sql,/^BEGIN;/);assert.match(sql,/COMMIT;\s*$/);assert.doesNotMatch(sql,/DROP\s+(TABLE|COLUMN)|TRUNCATE/i);assert.match(sql,/media_assets_workspace_sha_uq/);assert.match(sql,/property_identity_links_a_idx/);assert.match(sql,/own_listing_details_workspace_property_idx/);});
