import test from 'node:test';
import assert from 'node:assert/strict';
import {CollectorState,COLLECTOR_STATES} from '../bridge/whatsapp-secondary/collector-state.js';
import {downloadMessageMedia,MAX_MEDIA_CHUNK_BYTES} from '../bridge/whatsapp-secondary/media-collector.js';
import {buildMarketIndex,deduplicateTemporal,naturalMarketQuery} from '../secondary-whatsapp/market-intelligence.js';
import {createCollectorStatusHandler} from '../netlify/functions/secondary-whatsapp-collector-status.js';
import {createMediaIngestHandler} from '../netlify/functions/secondary-whatsapp-media-ingest.js';
import {createRadarFeedHandler} from '../netlify/functions/secondary-whatsapp-radar-feed.js';
import {createIntelligenceHandler} from '../netlify/functions/secondary-whatsapp-intelligence.js';

test('QR es efímero y desaparece al quedar listo',()=>{let now=1_000;const state=new CollectorState({now:()=>now});state.setQr('data:image/png;base64,qr',500);assert.equal(state.snapshot().qr_available,true);now=1_501;assert.equal(state.snapshot().qr_available,false);state.ready();assert.equal(state.state,COLLECTOR_STATES.READY);assert.equal(state.snapshot().qr_data_url,null);});
test('multimedia real se fragmenta y conserva hash',async()=>{const bytes=Buffer.alloc(MAX_MEDIA_CHUNK_BYTES+10,7),media=await downloadMessageMedia({hasMedia:true,id:{_serialized:'m1'},downloadMedia:async()=>({data:bytes.toString('base64'),mimetype:'image/jpeg',filename:'foto.jpg'})});assert.equal(media.chunks.length,2);assert.equal(media.sizeBytes,bytes.length);assert.match(media.sha256,/^[a-f0-9]{64}$/);});
test('deduplicación temporal e índice de mercado',()=>{const event={groupId:'g',authorId:'a',timestamp:'2026-09-08T10:00:00Z',text:'Apartamento Mañongo $75.000'},result=deduplicateTemporal([event,{...event,messageId:'2'}]);assert.equal(result.unique.length,1);assert.equal(result.duplicates.length,1);const properties=[{zone:'Mañongo',property_type:'Apartamento',price_usd:75000,area_m2:100,bedrooms:3},{zone:'Mañongo',property_type:'Apartamento',price_usd:85000,area_m2:100,bedrooms:3}];assert.deepEqual(buildMarketIndex(properties)[0],{zone:'Mañongo',type:'Apartamento',count:2,median_price_usd:80000,median_area_m2:100,median_price_m2_usd:800});assert.equal(naturalMarketQuery('apartamento mañongo hasta 80000 3 habitaciones',properties).length,1);});
test('estado collector oculta M2M y entrega QR',async()=>{const handler=createCollectorStatusHandler({env:{RADAR_COLLECTOR_URL:'https://collector.example',RADAR_COLLECTOR_M2M_TOKEN:'secret'},fetchImpl:async(_url,options)=>{assert.equal(options.headers.authorization,'Bearer secret');return {ok:true,json:async()=>({state:'WAITING_QR',qr_available:true,qr_data_url:'data:image/png;base64,qr'})};}}),response=await handler({httpMethod:'GET'}),body=JSON.parse(response.body);assert.equal(body.qr_available,true);assert.equal(response.body.includes('secret'),false);});
test('media ingest exige M2M y almacena original + manifest',async()=>{const rows=new Map(),store={set:async(key,value,options)=>rows.set(key,{value,options}),setJSON:async(key,value)=>rows.set(key,{value})},handler=createMediaIngestHandler({env:{RADAR_COLLECTOR_M2M_TOKEN:'secret'},storeFactory:()=>store}),sha='a'.repeat(64),base={httpMethod:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sha256:sha,mime_type:'image/jpeg',filename:'x.jpg',message_id:'m1',chunk_index:0,chunk_total:1,data_base64:Buffer.from('image').toString('base64')})};assert.equal((await handler(base)).statusCode,401);assert.equal((await handler({...base,headers:{...base.headers,authorization:'Bearer secret'}})).statusCode,202);assert.ok(rows.has(`original/${sha}/manifest`));});
test('feed Radar solo admite navegación same-origin y mantiene cursor',async()=>{const queue={list:async input=>({events:[{messageId:'m1'}],nextCursor:'event-0000000000000-m1',hasMore:false,...input})},handler=createRadarFeedHandler({queueFactory:async()=>queue});assert.equal((await handler({httpMethod:'GET',headers:{'sec-fetch-site':'cross-site'},queryStringParameters:{}})).statusCode,403);const ok=await handler({httpMethod:'GET',headers:{'sec-fetch-site':'same-origin'},queryStringParameters:{limit:'25'}});assert.equal(JSON.parse(ok.body).events.length,1);});
test('extracción multimodal M2M guarda inteligencia estructurada',async()=>{const rows=new Map(),store={get:async()=>null,setJSON:async(key,value)=>rows.set(key,value)},handler=createIntelligenceHandler({env:{RADAR_COLLECTOR_M2M_TOKEN:'secret'},storeFactory:()=>store,fetchImpl:async()=>({ok:true,json:async()=>({output_text:'{"is_real_estate":true,"property_type":"Apartamento","price_usd":75000}'})})}),response=await handler({httpMethod:'POST',headers:{authorization:'Bearer secret','content-type':'application/json'},body:JSON.stringify({messageId:'ai-1',text:'Apartamento en venta $75.000'})}),body=JSON.parse(response.body);assert.equal(response.statusCode,200);assert.equal(body.result.price_usd,75000);assert.ok(rows.has('message/ai-1'));});
