import {AppendOnlyEventStore} from './event-store.js';
import {sha256,uuidV7} from './ids.js';

export const DEFAULT_WORKSPACE_ID='00000000-0000-7000-8000-000000000001';
export const GROUP_COVERAGE_STATUSES=Object.freeze(['ZIP_ONLY','PENDING_SECONDARY','DUAL','SECONDARY_PRIMARY','SECONDARY_ONLY','INACTIVE']);
export const MESSAGE_CLASSIFICATIONS=Object.freeze(['PROPERTY','REQUEST','PRICE_UPDATE','AVAILABILITY_UPDATE','FEATURE_UPDATE','CONTACT_UPDATE','MEDIA_ONLY','VOICE_INFORMATION','REPOST','NOISE','UNKNOWN']);
const nowIso=clock=>new Date(clock()).toISOString();

export class RadarCoreFoundation{
  constructor({workspaceId=DEFAULT_WORKSPACE_ID,clock=Date.now,cryptoImpl=globalThis.crypto,logger=()=>{}}={}){
    this.workspaceId=workspaceId;this.clock=clock;this.crypto=cryptoImpl;this.logger=logger;
    this.events=new AppendOnlyEventStore();this.workspaces=new Map();this.channels=new Map();this.threads=new Map();this.coverage=new Map();this.importBatches=new Map();this.ingestionRuns=new Map();this.messages=new Map();this.messageKeys=new Map();this.evidence=new Map();this.properties=new Map();this.canonicalFacts=new Map();this.identityIndex=new Map();this.propertySources=new Map();this.sourceLinkKeys=new Map();this.idempotency=new Map();this.devices=new Map();this.clientMutations=new Map();this.syncChanges=[];
    this.workspaces.set(workspaceId,{id:workspaceId,name:'Emperatriz Radar',timezone:'America/Caracas',country_code:'VE',default_currency:'USD',created_at:nowIso(clock),updated_at:nowIso(clock)});
  }
  id(){return uuidV7({now:this.clock(),cryptoImpl:this.crypto});}
  emit(event_type,aggregate_type,aggregate_id,payload_json,{correlation_id=this.id(),causation_id=null,idempotency_key=null,actor_type='system'}={}){
    const at=nowIso(this.clock);return this.events.append({id:this.id(),workspace_id:this.workspaceId,event_type,aggregate_type,aggregate_id,schema_version:1,payload_json,occurred_at:at,recorded_at:at,actor_type,actor_id:null,correlation_id,causation_id,idempotency_key});
  }
  createChannel(input){const id=input.id||this.id(),at=nowIso(this.clock),row={id,workspace_id:this.workspaceId,channel_type:input.channel_type,account_role:input.account_role||'NONE',mode:input.mode||'MANUAL',enabled:input.enabled!==false,fallback_enabled:input.fallback_enabled!==false,adapter_version:input.adapter_version||'legacy-compatible',external_account_ref:input.external_account_ref||null,created_at:at,updated_at:at};this.channels.set(id,row);return row;}
  upsertThread(input){const id=input.id||this.id(),old=this.threads.get(id),at=nowIso(this.clock),row={id,workspace_id:this.workspaceId,ingestion_channel_id:input.ingestion_channel_id,external_thread_id:input.external_thread_id||null,thread_type:input.thread_type||'whatsapp_group',name:input.name||'',metadata_json:structuredClone(input.metadata_json||{}),first_seen_at:old?.first_seen_at||at,last_seen_at:input.last_seen_at||at,created_at:old?.created_at||at,updated_at:at};this.threads.set(id,row);return row;}
  setGroupCoverage(input){if(!GROUP_COVERAGE_STATUSES.includes(input.coverage_status))throw new Error('invalid_coverage_status');const key=`${this.workspaceId}:${input.group_identifier}`,old=this.coverage.get(key),at=nowIso(this.clock),row={id:old?.id||this.id(),workspace_id:this.workspaceId,group_identifier:input.group_identifier,group_name:input.group_name||old?.group_name||'',zip_available:input.zip_available??old?.zip_available??true,secondary_available:input.secondary_available??old?.secondary_available??false,coverage_status:input.coverage_status,secondary_joined_at:input.secondary_joined_at??old?.secondary_joined_at??null,last_zip_activity_at:input.last_zip_activity_at??old?.last_zip_activity_at??null,last_secondary_activity_at:input.last_secondary_activity_at??old?.last_secondary_activity_at??null,zip_fallback_enabled:input.zip_fallback_enabled??old?.zip_fallback_enabled??true,created_at:old?.created_at||at,updated_at:at};this.coverage.set(key,row);return row;}
  async beginImportBatch({fileBytes,fileName,threadId,deviceId=null,rangeStart=null,rangeEnd=null,force=false}){
    const file_hash=await sha256(fileBytes,this.crypto),key=`import:${this.workspaceId}:${file_hash}`,existing=this.idempotency.get(key);
    if(existing&&!force){this.logger({event:'DUPLICATE_AVOIDED',operation:'import_batch'});return {status:'already_processed',batch:this.importBatches.get(existing.result_id)};}
    const id=this.id(),correlation_id=this.id(),at=nowIso(this.clock),batch={id,workspace_id:this.workspaceId,device_id:deviceId,file_hash,source_filename:fileName,source_thread_id:threadId,range_start:rangeStart,range_end:rangeEnd,messages_detected:0,messages_imported:0,duplicates_detected:0,errors_count:0,started_at:at,finished_at:null,status:'STARTED',correlation_id};this.importBatches.set(id,batch);this.idempotency.set(key,{key,result_id:id,created_at:at});this.emit('IMPORT_BATCH_STARTED','import_batch',id,{file_hash,source_filename:fileName},{correlation_id,idempotency_key:key});this.logger({event:'IMPORT_BATCH_STARTED',batchId:id});return {status:'started',batch};
  }
  completeImportBatch(id,counts={}){const row=this.importBatches.get(id);if(!row)throw new Error('import_batch_not_found');Object.assign(row,{messages_detected:counts.messages_detected||0,messages_imported:counts.messages_imported||0,duplicates_detected:counts.duplicates_detected||0,errors_count:counts.errors_count||0,finished_at:nowIso(this.clock),status:counts.errors_count?'COMPLETED_WITH_ERRORS':'COMPLETED'});this.emit('IMPORT_BATCH_COMPLETED','import_batch',id,{...counts},{correlation_id:row.correlation_id});this.logger({event:'IMPORT_BATCH_COMPLETED',batchId:id});return row;}
  startIngestionRun(channelId,metadata_json={}){const id=this.id(),correlation_id=this.id(),at=nowIso(this.clock),row={id,workspace_id:this.workspaceId,ingestion_channel_id:channelId,started_at:at,finished_at:null,last_heartbeat_at:at,messages_received:0,media_received:0,duplicates_detected:0,errors_count:0,status:'STARTED',cursor:null,metadata_json:structuredClone(metadata_json),correlation_id};this.ingestionRuns.set(id,row);this.emit('INGESTION_RUN_STARTED','ingestion_run',id,{channelId},{correlation_id});return row;}
  completeIngestionRun(id,counts={}){const row=this.ingestionRuns.get(id);if(!row)throw new Error('ingestion_run_not_found');Object.assign(row,counts,{finished_at:nowIso(this.clock),status:counts.errors_count?'COMPLETED_WITH_ERRORS':'COMPLETED'});this.emit('INGESTION_RUN_COMPLETED','ingestion_run',id,{...counts},{correlation_id:row.correlation_id});return row;}
  async receiveSourceMessage(input,{correlation_id=this.id(),causation_id=null}={}){
    const content_hash=input.content_hash||await sha256(String(input.raw_text||''),this.crypto);const externalKey=input.external_message_id?`${input.ingestion_channel_id}:${input.source_thread_id}:${input.external_message_id}`:null;
    const fallbackKey=`${input.ingestion_channel_id}:${input.source_thread_id}:${content_hash}:${input.published_at||input.received_at||''}`;const key=externalKey||fallbackKey,existing=this.messageKeys.get(key);
    if(existing){this.logger({event:'DUPLICATE_AVOIDED',operation:'source_message',messageId:existing});return {duplicate:true,message:this.messages.get(existing)};}
    const id=input.id||this.id(),published=input.published_at?Date.parse(input.published_at):NaN,received=input.received_at?Date.parse(input.received_at):this.clock(),at=nowIso(this.clock),classification=MESSAGE_CLASSIFICATIONS.includes(input.classification)?input.classification:'UNKNOWN';
    const row={id,workspace_id:this.workspaceId,source_thread_id:input.source_thread_id,ingestion_channel_id:input.ingestion_channel_id,external_message_id:input.external_message_id||null,author_external_ref:input.author_external_ref||null,raw_text:String(input.raw_text||''),source_url:input.source_url||null,published_at:input.published_at||null,received_at:input.received_at||at,ingested_at:at,content_hash,classification,classification_confidence:input.classification_confidence??null,classification_version:input.classification_version||null,future_date_flag:Number.isFinite(published)&&published>received,metadata_json:structuredClone(input.metadata_json||{}),created_at:at};
    this.messages.set(id,Object.freeze(row));this.messageKeys.set(key,id);const event=this.emit('SOURCE_MESSAGE_RECEIVED','source_message',id,{classification,content_hash},{correlation_id,causation_id,idempotency_key:key});return {duplicate:false,message:row,event};
  }
  observeFact(input,{correlation_id,causation_id}={}){
    if(!input.source_message_id&&!input.source_attachment_id&&!input.source_url)throw new Error('evidence_source_required');
    const id=this.id(),at=nowIso(this.clock),row={id,workspace_id:this.workspaceId,entity_type:input.entity_type,entity_id:input.entity_id||null,field_key:input.field_key,value_json:structuredClone(input.value_json),normalized_text:input.normalized_text||null,source_message_id:input.source_message_id||null,source_attachment_id:input.source_attachment_id||null,source_url:input.source_url||null,evidence_method:input.evidence_method||'description',evidence_locator:input.evidence_locator||null,confidence:input.confidence??0.5,status:input.status||'OBSERVED',observed_at:input.observed_at||at,valid_from:input.valid_from||null,valid_to:input.valid_to||null,extractor_version:input.extractor_version||null,confirmed_by:null,confirmed_at:null,created_at:at};this.evidence.set(id,row);const event=this.emit('FACT_EXTRACTED','evidence_fact',id,{field_key:row.field_key,source_message_id:row.source_message_id},{correlation_id,causation_id});return {fact:row,event};
  }
  selectCanonicalFact({property_id,field_key,evidence_fact_id,selection_method='highest_confirmed_confidence',selected_by=null},{correlation_id,causation_id}={}){
    const property=this.properties.get(property_id),fact=this.evidence.get(evidence_fact_id);if(!property)throw new Error('property_not_found');if(!fact)throw new Error('evidence_fact_not_found');
    const row={property_id,field_key,evidence_fact_id,value_json:structuredClone(fact.value_json),selection_method,selected_at:nowIso(this.clock),selected_by};this.canonicalFacts.set(`${property_id}:${field_key}`,row);
    property[field_key]=structuredClone(fact.value_json);property.canonical_version+=1;property.updated_at=row.selected_at;this.emit('PROPERTY_FIELD_CHANGED','master_property',property_id,{field_key,evidence_fact_id},{correlation_id,causation_id});return row;
  }
  createOrLinkProperty({identity_key,fields={},source_message_id,relation_type='original',identity_confidence=null,correlation_id,causation_id}){
    if(!source_message_id||!this.messages.has(source_message_id))throw new Error('source_message_required');let property_id=this.identityIndex.get(identity_key),created=false,property;
    if(!property_id){property_id=this.id();created=true;const at=nowIso(this.clock);property={id:property_id,workspace_id:this.workspaceId,canonical_code:`RADAR-${property_id.slice(0,8)}`,operation:fields.operation||null,property_type:fields.property_type||null,territory_id:fields.territory_id||null,residence_name:fields.residence_name||null,price_usd:fields.price_usd??null,currency:fields.currency||'USD',area_m2:fields.area_m2??null,land_area_m2:fields.land_area_m2??null,bedrooms:fields.bedrooms??null,bathrooms:fields.bathrooms??null,half_bathrooms:fields.half_bathrooms??null,parking:fields.parking??null,status:fields.status||'UNKNOWN',ownership_scope:fields.ownership_scope||'UNKNOWN',first_seen_at:at,last_seen_at:at,last_verified_at:null,readiness_status:fields.readiness_status||'ENRICHING',identity_confidence,canonical_version:1,created_at:at,updated_at:at,deleted_at:null};this.properties.set(property_id,property);this.identityIndex.set(identity_key,property_id);this.emit('PROPERTY_MASTER_CREATED','master_property',property_id,{identity_key},{correlation_id,causation_id});}else property=this.properties.get(property_id);
    return {created,property,...this.linkSourceToProperty({property_id,source_message_id,relation_type,identity_confidence,correlation_id,causation_id})};
  }
  linkSourceToProperty({property_id,source_message_id,relation_type='original',identity_confidence=null,correlation_id,causation_id}){if(!this.properties.has(property_id))throw new Error('property_not_found');if(!this.messages.has(source_message_id))throw new Error('source_message_required');const linkKey=`${property_id}:${source_message_id}`,existing=this.sourceLinkKeys.get(linkKey);if(existing)return {source:this.propertySources.get(existing),duplicateSource:true};const source={id:this.id(),workspace_id:this.workspaceId,property_id,source_message_id,relation_type,identity_confidence,linked_at:nowIso(this.clock),linked_by:null};this.propertySources.set(source.id,source);this.sourceLinkKeys.set(linkKey,source.id);this.emit('PROPERTY_SOURCE_LINKED','master_property',property_id,{source_message_id,relation_type},{correlation_id,causation_id});return {source,duplicateSource:false};}
  registerDevice(input){const row={id:input.id||this.id(),workspace_id:this.workspaceId,device_name:input.device_name||'Radar device',last_seen_at:nowIso(this.clock),last_sync_sequence:0};this.devices.set(row.id,row);return row;}
  applyClientMutation(input,apply){if(this.clientMutations.has(input.mutation_id))return {duplicate:true,mutation:this.clientMutations.get(input.mutation_id)};const at=nowIso(this.clock),row={mutation_id:input.mutation_id,device_id:input.device_id,workspace_id:this.workspaceId,entity_type:input.entity_type,entity_id:input.entity_id,operation:input.operation,payload_json:structuredClone(input.payload_json||{}),created_at:input.created_at||at,status:'RECEIVED',applied_at:null};this.clientMutations.set(row.mutation_id,row);const received=this.emit('SYNC_MUTATION_RECEIVED','client_mutation',row.mutation_id,{entity_type:row.entity_type},{idempotency_key:row.mutation_id});try{apply(row);row.status='APPLIED';row.applied_at=nowIso(this.clock);const sequence_id=this.syncChanges.length+1;this.syncChanges.push({sequence_id,workspace_id:this.workspaceId,entity_type:row.entity_type,entity_id:row.entity_id,operation:row.operation,row_version:1,changed_at:row.applied_at});this.emit('SYNC_MUTATION_APPLIED','client_mutation',row.mutation_id,{sequence_id},{correlation_id:received.correlation_id,causation_id:received.id});return {duplicate:false,mutation:row};}catch(error){row.status='FAILED';this.logger({event:'SYNC_MUTATION_FAILED',errorName:error?.name||'Error'});throw error;}}
}
