(()=>{
function waitReady(){if(typeof props==='undefined'||typeof render!=='function'||typeof resolve!=='function'){setTimeout(waitReady,250);return}applyPatch()}
function allPhones(x){let ms=String(x||'').match(/(?:\+?58\s*)?(?:0?)(?:412|414|416|424|426)[\s().-]*\d{3}[\s.-]*\d{4}/g)||[];return[...new Set(ms.map(v=>{let d=v.replace(/\D/g,'').replace(/^58/,'').replace(/^0/,'');return d.length===10?'+58'+d:null}).filter(Boolean))]}
function rawPhone(raw){let a=allPhones(raw);if(a.length===1)return a[0];for(let line of String(raw||'').split(/\n/)){if(/contact|whatsapp|asesor|info|telefono|tel[eé]fono|tlf/i.test(line)){let p=allPhones(line);if(p.length===1)return p[0]}}return null}
function strictCount(n,k,t){let ps={h:[/(\d{1,2})\s*(?:habitaciones?|hab\.?|dormitorios?)\b/,/\b(?:habitaciones?|hab\.?)\s*[:\-]?\s*(\d{1,2})\b/,/\b(\d{1,2})\s*h\b/],b:[/(\d{1,2})\s*(?:banos?|baños?)\b/,/\b(?:banos?|baños?)\s*[:\-]?\s*(\d{1,2})\b/,/\b(\d{1,2})\s*b\b/],e:[/(\d{1,2})\s*(?:puestos?(?:\s+de\s+estacionamiento)?|ptos?\.?|estacionamientos?)\b/,/\b(?:puestos?(?:\s+de\s+estacionamiento)?|ptos?\.?|estacionamientos?)\s*[:\-]?\s*(\d{1,2})\b/,/\b(\d{1,2})\s*p\b/]};for(let r of ps[k]){let m=n.match(r);if(m){let v=+m[1];if((k==='h'||k==='b')&&v>20)return null;if(k==='e'&&['Apartamento','Penthouse','Townhouse','Casa'].includes(t)&&v>8)return null;if(k==='e'&&v>50)return null;return v}}return null}
function amountCandidates(raw){let out=[],re=/(?:USD|US\$|\$)?\s*(\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{1,2})?|\d{3,7}|\d{1,4}(?:[.,]\d{1,2})?)\s*(k|mil)?\s*(?:USD|d[oó]lares?|\$)?/gi,m;while((m=re.exec(raw))){let v=money(m[1]);if(v&&m[2])v*=1000;if(v>=100)out.push({v,context:norm(raw.slice(Math.max(0,m.index-28),Math.min(raw.length,re.lastIndex+28)))})}return out}
function contextPrice(raw,kind){let a=amountCandidates(raw),words=kind==='Venta'?['venta','vendo','precio de venta','inversion']:['alquiler','canon','renta','arrendamiento'];let hit=a.find(x=>words.some(w=>x.context.includes(norm(w))));if(hit)return hit.v;let vals=[...new Set(a.map(x=>x.v))];if(kind==='Venta'){let hi=vals.filter(v=>v>=5000);return hi.length?Math.max(...hi):null}let lo=vals.filter(v=>v>=100&&v<=5000);return lo.length?Math.min(...lo):null}
function enrich(p){let n=norm(p.raw||''),T=type(n),O=operation(n);p.tipo=T||p.tipo;p.op=O;p.h=strictCount(n,'h',p.tipo);p.b=strictCount(n,'b',p.tipo);p.e=strictCount(n,'e',p.tipo);if(O==='Venta'||O==='Venta/Alquiler')p.salePrice=contextPrice(p.raw,'Venta');if(O==='Alquiler'||O==='Venta/Alquiler')p.rentPrice=contextPrice(p.raw,'Alquiler');if(O==='Venta'&&p.salePrice)p.precio=p.salePrice;if(O==='Alquiler'&&p.rentPrice)p.precio=p.rentPrice;p.senderPhone=allPhones(p.sender)[0]||null;p.messagePhone=rawPhone(p.raw);resolve(p);return p}
resolve=function(p){p.phone=null;p.contactName=null;if(p.senderPhone||allPhones(p.sender)[0]){p.phone=p.senderPhone||allPhones(p.sender)[0];p.contactSource='número del emisor';return p}let a=cmap.get(key(p.sender))||[],u=[...new Set(a.map(x=>x.phone).filter(Boolean))];if(u.length===1){p.phone=u[0];p.contactName=a[0].name;p.contactSource='contacto iPhone del emisor';return p}let rp=p.messagePhone||rawPhone(p.raw);if(rp){p.phone=rp;p.contactSource='número publicado por el captador';return p}p.contactSource=u.length>1?'nombre ambiguo en contactos':'captador no resuelto';return p};
let oldProp=prop;prop=function(m,src){let p=oldProp(m,src);return p?enrich(p):p};
function priceForDisplay(p){let o=$('#op').value;if(o==='Venta')return p.salePrice||p.precio;if(o==='Alquiler')return p.rentPrice||p.precio;return p.precio}
render=function(a){$('#count').textContent='('+a.length+')';if(!a.length){$('#results').className='empty';$('#results').innerHTML='No encontré inventario vigente con esos criterios.';return}$('#results').className='';$('#results').innerHTML=a.slice(0,250).map(p=>{enrich(p);let msg=PREFIX+'\n\n'+p.raw,L=[p.zona,p.municipio].filter(Boolean).join(' · ')||'Ubicación por confirmar',F=(p.features||[]).slice(0,6).map(x=>'<span class="pill">'+esc(x)+'</span>').join(''),capt=esc(p.contactName||p.sender||'Emisor sin identificar'),dual=p.op==='Venta/Alquiler'&&!$('#op').value,priceHtml=dual?'<div class="price">'+(p.salePrice?'Venta '+cash(p.salePrice):'Venta —')+'<br><small>'+(p.rentPrice?'Alquiler '+cash(p.rentPrice):'Alquiler —')+'</small></div>':'<div class="price">'+cash(priceForDisplay(p))+'</div>',contact=p.phone?'<button class="primary wa" data-phone="'+esc(p.phone)+'" data-msg="'+esc(msg)+'">WhatsApp del captador</button><div class="hint">'+esc(p.contactSource)+'</div>':'<button class="wa" disabled style="opacity:.58">Captador no resuelto</button><div class="hint">Emisor: '+capt+'. Importa tus contactos VCF si este nombre está guardado en tu iPhone.</div>';return'<article class="card"><div class="head"><div><div><span class="pill">'+esc(p.op||'Operación por confirmar')+'</span>'+(p.tipo?'<span class="pill">'+esc(p.tipo)+'</span>':'')+'</div><div class="loc">'+esc(L)+'</div><div class="sender"><b>Captador:</b> '+capt+'</div></div><div>'+priceHtml+'<div class="age">'+(p.age===0?'hoy':p.age===1?'hace 1 día':'hace '+p.age+' días')+'</div></div></div><div class="specs"><div class="spec"><b>'+esc(p.m2??'—')+'</b><span>m²</span></div><div class="spec"><b>'+esc(p.h??'—')+'</b><span>HAB</span></div><div class="spec"><b>'+esc(p.b??'—')+'</b><span>BAÑOS</span></div><div class="spec"><b>'+esc(p.e??'—')+'</b><span>PUESTOS</span></div></div><div class="features">'+F+'</div>'+contact+'<details><summary>Mensaje original</summary><pre>'+esc(p.raw)+'</pre></details></article>'}).join('');document.querySelectorAll('[data-phone]').forEach(b=>b.onclick=()=>location.href='https://wa.me/'+b.dataset.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(b.dataset.msg))};
function queryIntent(raw){let work=norm(raw),I={type:null,municipio:null,zona:null,op:null,features:[],free:[]},T=type(work);if(T){I.type=T;for(let[t,aa]of types)if(t===T)for(let x of aa)work=work.replaceAll(norm(x),' ')}let L=loc(work);if(L.municipio){I.municipio=L.municipio;I.zona=L.zona;if(L.zona)for(let x of zones[L.municipio][L.zona])work=work.replaceAll(norm(x),' ');else work=work.replaceAll(norm(L.municipio),' ')}if(/\bventa\b/.test(work)){I.op='Venta';work=work.replace(/\bventa\b/g,' ')}else if(/\balquiler\b/.test(work)){I.op='Alquiler';work=work.replace(/\balquiler\b/g,' ')}for(let[k,aa]of Object.entries(fmap))if(aa.some(x=>work.includes(norm(x)))){I.features.push(k);for(let x of aa)work=work.replaceAll(norm(x),' ')}I.free=work.split(/\s+/).filter(x=>x.length>1);return I}
function matchOp(p,o){if(!o)return true;if(o==='?')return !p.op;if(o==='Venta')return p.op==='Venta'||(p.op==='Venta/Alquiler'&&!!p.salePrice);if(o==='Alquiler')return p.op==='Alquiler'||(p.op==='Venta/Alquiler'&&!!p.rentPrice);return p.op===o}
search=function(){let I=queryIntent($('#q').value),pm=+$('#pmax').value||0,hm=+$('#hmin').value||0,bm=+$('#bmin').value||0,em=+$('#emin').value||0,mm=+$('#mmin').value||0,o=$('#op').value||I.op,m=$('#municipio').value||I.municipio,z=$('#zona').value||I.zona,t=$('#tipo').value||I.type,fs=[...new Set([$('#ft').value,...I.features].filter(Boolean))];let a=props.filter(p=>{enrich(p);if(m&&p.municipio!==m)return false;if(z&&p.zona!==z)return false;if(t&&p.tipo!==t)return false;if(!matchOp(p,o))return false;let pv=o==='Venta'?(p.salePrice||p.precio):o==='Alquiler'?(p.rentPrice||p.precio):p.precio;if(pm&&(!pv||pv>pm))return false;if(hm&&(p.h==null||p.h<hm))return false;if(bm&&(p.b==null||p.b<bm))return false;if(em&&(p.e==null||p.e<em))return false;if(mm&&(p.m2==null||p.m2<mm))return false;if(fs.some(f=>!(p.features||[]).includes(f)))return false;let hay=norm([p.tipo,p.op,p.municipio,p.zona,p.sender,p.raw,(p.features||[]).join(' ')].join(' '));return I.free.every(w=>hay.includes(w))}).sort((a,b)=>b.ts-a.ts);render(a)};
function applyPatch(){try{Object.assign(zones['San Diego'],{'Terrazas de San Diego':['terrazas de san diego'],'Villas del Campo':['villas del campo'],'Los Frailes':['los frailes']});Object.assign(zones.Valencia,{'Valle Blanco':['valle blanco'],'Altos de Guataparo':['altos de guataparo']});props.forEach(enrich);if(typeof puts==='function'&&db)puts('properties',props).catch(()=>{});$('#searchBtn').onclick=search;document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{$('#op').value=b.dataset.op;search()});document.querySelectorAll('[data-ft]').forEach(b=>b.onclick=()=>{$('#ft').value=b.dataset.ft;search()});render(props);stat();let n=document.querySelector('#status');if(n)n.textContent='Motor V2 activo · captador directo + búsqueda estructurada.'}catch(e){console.error('patch-v2',e)}}
waitReady();
})();